name: PyPi Release

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine
      - name: Build dist packages
        run: python setup.py sdist bdist_wheel
      - name: Upload packages
        run: python -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TWINE_TOKEN }}
